<a href="https://colab.research.google.com/github/Qvery-mm/NumericMethods_2/blob/main/lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Вычислительный практикум
# Задание №3
### Полная проблема собственных значений. Метод Якоби. Частичная проблема собственных. значений (степенной, скалярных приблтжений).
## Ковальчуков Александр
### 321 группа
### Вариант №6

In [ ]:
import numpy as np
from math import sqrt

def sign(x):
  if x > 0:
    return 1
  elif x < 0:
    return -1
  else:
    return 0

norm = np.linalg.norm

# Параметры задачи

In [ ]:
__A = np.array([[-0.95121, -0.09779, 0.35843],
              [ -0.09779, 0.61545, 0.02229],
              [0.35843, 0.022286, -0.95729]])


n  = __A.shape[0]

eps = 10**-6

# Метод Якоби

In [ ]:
X = np.eye(n)
A = __A.copy()

while True:
  # поиск максимального по модулю наддиагонального элемента
  m, i , j = 0, 0, 0
  for y in range(n - 1):
    for x in range(y + 1, n):
        if abs(A[y, x]) >=m:
          m, i , j = abs(A[y, x]), y, x
  
  if m < eps:
    break
  
  d = sqrt((A[i, i] - A[j, j])**2 + 4 * A[i, j]**2 ) 
  c = sqrt(1/2 * (1 + abs(A[i, i] - A[j, j] ) / d))
  s = sign( A[i, j] * (A[i,i] - A[j,j])) *  sqrt(1/2 * (1 - abs(A[i,i] - A[j,j]) / d))

  V = np.eye(n)
  V[i,i] = V[j,j]  = c
  V[i , j] = -s
  V[j, i] = s
  
  A =  np.dot(np.dot(V.T, A),  V)
  X = np.dot(X, V)

eigenvalues = np.diag(A)
eigenvectors = [X[: ,0].reshape(n, 1), X[:, 1].reshape(n, 1), X[:, 2].reshape(n, 1)]
for i in range(n):
  eigenvectors[i] /= norm(eigenvectors[i], 2)


### Найденные собственные значения и векторы:

In [ ]:
print(eigenvalues, end='\n\n')
for i in range(n):
  print(eigenvectors[i], end='\n\n')

[-0.59816791  0.6215304  -1.31641249]

[[0.70574354]
 [0.04388178]
 [0.7071071 ]]

[[-6.20591453e-02]
 [ 9.98072474e-01]
 [ 9.05988548e-07]]

[[-0.70574409]
 [-0.0438831 ]
 [ 0.70710646]]



### Проверка, что $||A v_i - \lambda_i v_i ||_\infty \approx 0$




In [ ]:
for i in range(n):
  diff = np.dot(__A, eigenvectors[i]) - eigenvalues[i] * eigenvectors[i]
  print(norm(diff, np.inf))

2.4747912908650027e-06
2.2466863302356685e-06
1.152522521863375e-11


# Степенной метод

In [ ]:
A = __A.copy()
eps = 10**-3
y0 = y1 = np.random.rand(n, 1)
counter = 0

while True:
  counter += 1
  y0 = y1
  y1 = np.dot(A, y0)
  lamb = np.mean(y1) / np.mean(y0)
  y1 = y1 / norm(y1, 2)
  # апостриорная оценка
  if norm(np.dot(A, y1) - lamb * y1, 2) / norm(y1, 2) < eps:
    break

print("lambda = ", lamb, end = '\n\n')
print("v = ", y1, end = '\n\n')
print("counter ", counter)

lambda =  -1.3164124883445347

v =  [[-0.70574409]
 [-0.0438831 ]
 [ 0.70710646]]

counter  36


# Метод скалярных произведений

In [ ]:
A = __A.copy()
eps = 10**-3
y0 = y1 = np.random.rand(n, 1)
counter = 0

while True:
  counter += 1
  y0 = y1
  y1 = np.dot(A, y0)
  lamb = np.dot(y1.T, y0) / np.dot(y0.T, y0)
  y1 = y1 / norm(y1, 2)
  # апостриорная оценка
  if norm(np.dot(A, y1) - lamb * y1, 2) / norm(y1, 2) < eps:
    break

print("lambda = ", lamb, end = '\n\n')
print("v = ", y1, end = '\n\n')
print("counter ", counter)

lambda =  [[-1.31641249]]

v =  [[ 0.70574409]
 [ 0.0438831 ]
 [-0.70710646]]

counter  30


### Количество итераций хотя и зависит от начального приближения $Y_0$, у метода скалярных произведений оно в среднем оказывается меньше.