<a href="https://colab.research.google.com/github/Qvery-mm/NumericMethods_2/blob/main/lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Вычислительный практикум
# Задание №5
### Жесткие системы.
## Ковальчуков Александр
### 321 группа
### Вариант №6

# Условия задачи

In [150]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
A = np.array([[-125, 123.3], 
              [123.3, -123]])
y0 = np.array([[1], 
              [1]])
n = A.shape[0]

# Точное решение

In [151]:
eigenvalues = np.linalg.eig(A)[0]
eigenvectors = np.linalg.eig(A)[1]
U = np.linalg.eig(A)[1]
ff = np.linalg.solve(U, y0)
W = ff.T * U

In [152]:
def f(t):
  x = np.exp(t * eigenvalues)
  return np.dot(W, x.T)

def exact(a, b, h):
  ans = []
  m = int((b - a) / h) + 1
  for i in range(m):
    ans.append(f(a + i * h).reshape(1, n))
  return ans

# Метод Эйлера

In [153]:
def euler(a, b, h):
  y = y0
  m = int((b - a) / h)
  E = np.eye(n)
  ans = [y.reshape(1, n)]
  for i in range(m):
    y = np.dot(E + h * A,  y)
    ans.append(y.reshape(1, n))
  return ans  

In [154]:
euler(0, 0.5, 0.1)

[array([[1, 1]]),
 array([[0.83, 1.03]]),
 array([[ 3.1549, -1.4051]]),
 array([[-53.606233,  54.777547]]),
 array([[ 1291.87883401, -1279.95113399]]),
 array([[-30638.40407321,  30392.31383743]])]

# Обратный метод Эйлера

In [155]:
def reverse_euler(a, b, h):
  y = y0
  m = int((b - a) / h)
  E = np.eye(n)
  ans = [y.reshape(1, n)]
  for i in range(m):
    y = np.dot(np.linalg.inv(E - h * A),  y)
    ans.append(y.reshape(1, n))
  return ans  

In [156]:
reverse_euler(0, 0.5, 0.1)

[array([[1, 1]]),
 array([[0.93128545, 0.9385526 ]]),
 array([[0.87054842, 0.87762516]]),
 array([[0.8138996 , 0.82052685]]),
 array([[0.76094199, 0.76713847]]),
 array([[0.71143035, 0.71722366]])]

# Интерполяционный метод Адамса 2 порядка

In [157]:
def adams_2ord(a, b, h):
  y = y0
  m = int((b - a) / h)
  E = np.eye(n)
  ans = [y.reshape(1, n)]
  for i in range(m):
    y = np.dot(np.dot(np.linalg.inv(E - h * A / 2), E + h * A / 2), y)
    ans.append(y.reshape(1, n))
  return ans  

In [158]:
adams_2ord(0, 0.5, 0.1)

[array([[1, 1]]),
 array([[0.92548594, 0.93994696]]),
 array([[0.86941655, 0.87060796]]),
 array([[0.80569496, 0.81726314]]),
 array([[0.75597264, 0.75787072]]),
 array([[0.70133422, 0.71066611]])]

# Метод Эйлера устойчив при $h < 0.008087$

In [159]:
lamb = max(map(abs, eigenvalues))
h = 2 / lamb
h

0.008087210698287415

# Обратный метод Эйлера устойчив при всех $h$, поскольку с.ч $A$ отрицательны и c.ч. $(E - Ah)^{-1}$ по модулю меньше 1

# Метод Адамса 2 порядка устойчив при всех $h$, поскольку $\lambda_i ((E - hA)^{-1}(E + hA)) = \frac{1 + h \lambda_i(A)}{1 - h \lambda_i(A)}$, что по модулю меньше 1, когда c.ч. $A$ отрицательные

In [187]:
def compare(a, b, h):
  k = int((b - a) / h) + 1
  ex = np.array(exact(a, b, h)).reshape(k, 2)
  eu = np.array(euler(a, b, h)).reshape(k, 2)
  re_eu = np.array(reverse_euler(a, b, h)).reshape(k, 2)
  ad = np.array(adams_2ord(a, b, h)).reshape(k, 2)
  return pd.DataFrame( {"Точное y1": ex[:, 0], 
                      "Точное y2": ex[:, 1],
                      "М. Эйлера y1": ex[:, 0] - eu[:, 0],
                      "М. Эйлера y2": ex[:, 1] - eu[:, 1],
                      "Обр. м. Э y1": ex[:, 0] - re_eu[:, 0],
                      "Обр. м. Э y2": ex[:, 1] - re_eu[:, 1],
                      "м. Адамса y1": ex[:, 0] - ad[:, 0],
                      "м. Адамса y2": ex[:, 1] - ad[:, 1],
                       })

In [188]:
compare(0, 0.5, 0.1)

Точное y1  Точное y2  М. Эйлера y1  ...  Обр. м. Э y2  м. Адамса y1  м. Адамса y2
0   1.000000   1.000000      0.000000  ...  2.220446e-16      0.000000  2.220446e-16
1   0.928974   0.936539      0.098974  ... -2.013543e-03      0.003488 -3.407906e-03
2   0.866521   0.873577     -2.288379  ... -4.047756e-03     -0.002895  2.969436e-03
3   0.808267   0.814849     54.414500  ... -5.678324e-03      0.002572 -2.414608e-03
4   0.753929   0.760068  -1291.124906  ... -7.070584e-03     -0.002044  2.197168e-03
5   0.703243   0.708970  30639.107317  ... -8.253628e-03      0.001909 -1.696071e-03

[6 rows x 8 columns]

In [189]:
compare(0, 0.5, 0.05)

Точное y1  Точное y2  ...  м. Адамса y1  м. Адамса y2
0    1.000000   1.000000  ...      0.000000  2.220446e-16
1    0.961869   0.969702  ...      0.002941 -2.910642e-03
2    0.928974   0.936539  ...     -0.002113  2.109194e-03
3    0.897204   0.904511  ...      0.001539 -1.507612e-03
4    0.866521   0.873577  ...     -0.001091  1.106964e-03
5    0.836887   0.843702  ...      0.000811 -7.750601e-04
6    0.808267   0.814849  ...     -0.000558  5.871030e-04
7    0.780625   0.786982  ...      0.000434 -3.918892e-04
8    0.753929   0.760068  ...     -0.000278  3.180799e-04
9    0.728145   0.734074  ...      0.000239 -1.909017e-04
10   0.703243   0.708970  ...     -0.000131  1.793830e-04

[11 rows x 8 columns]

In [190]:
compare(0, 0.5, 0.001)

Точное y1  Точное y2  ...  м. Адамса y1  м. Адамса y2
0     1.000000   1.000000  ...  0.000000e+00  2.220446e-16
1     0.998415   1.000186  ...  4.042000e-06 -4.009295e-06
2     0.997026   1.000179  ...  6.308821e-06 -6.257750e-06
3     0.995790   1.000021  ...  7.385190e-06 -7.325369e-06
4     0.994674   0.999746  ...  7.684630e-06 -7.622335e-06
..         ...        ...  ...           ...           ...
496   0.705204   0.710946  ...  9.825150e-09  9.905158e-09
497   0.704713   0.710452  ...  9.838110e-09  9.918223e-09
498   0.704223   0.709958  ...  9.851047e-09  9.931265e-09
499   0.703733   0.709464  ...  9.863961e-09  9.944285e-09
500   0.703243   0.708970  ...  9.876852e-09  9.957281e-09

[501 rows x 8 columns]